# Generated by Django 6.1.1 on 2026-09-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('origin', 'follower'), name='unique_subscription'),
        ),
    ]
